package com.example.hackillinoisapp

import org.json.JSONObject

//I made this because functions do pass-by-value and not pass-by-reference
//Should've probably made this a nullable JSONObject
//https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS45LjEwIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiLyoqXG4gKiBZb3UgY2FuIGVkaXQsIHJ1biwgYW5kIHNoYXJlIHRoaXMgY29kZS5cbiAqIHBsYXkua290bGlubGFuZy5vcmdcbiAqL1xuZnVuIG1haW4oKSB7XG4gICAgLy92YXIgbnVtYmVyID0gYW5pbWFsU2l6ZSg0KVxuICAgIC8vcHJpbnRsbihudW1iZXIpXG4gICAgLy9jaGFuZ2VTaXplKG51bWJlcilcbiAgICAvL3ByaW50bG4obnVtYmVyKVxuICAgIC8vcHJpbnRsbihhbmltYWwuc2l6ZSlcbiAgICB2YXIgYW5pID0gQW5pbWFsKClcbiAgICBwcmludGxuKGFuaS5zaXplKVxuICAgIGFuaS5jaGFuZ2UoKVxuICAgIHByaW50bG4oYW5pLnNpemUpXG59XG5cbmZ1biBjaGFuZ2VTaXplKG4gOiBhbmltYWxTaXplKSB7XG4gICAgICAgIG4uc2l6ZSsrXG4gICAgfVxuXG5kYXRhIGNsYXNzIGFuaW1hbFNpemUodmFyIHNpemU6IEludClcblxuY2xhc3MgQW5pbWFsIHtcbiAgICB2YXIgc2l6ZSA9IGFuaW1hbFNpemUoMSlcbiAgICBcbiAgICB2YXIgbCA9IHRydWVcbiAgICBcbiAgICBmdW4gY2hhbmdlKCkge1xuICAgICAgICBpZiAodHJ1ZSkge1xuICAgICAgICBcdGNoYW5nZVNpemUoc2l6ZSlcbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgIGNoYW5nZVNpemUoc2l6ZSlcbiAgICAgICAgfVxuICAgICAgICBwcmludGxuKFwiXCIrc2l6ZStcImpcIilcbiAgICB9XG4gICAgXG4gICAgZnVuIGNoYW5nZVNpemUobiA6IGFuaW1hbFNpemUpIHtcbiAgICAgICAgbi5zaXplKytcbiAgICB9XG59In0=
data class WrapperJSON (
    var json: JSONObject
)

